### ISSUE TITLE
Problems with large package size

### ISSUE THREAD

**Issue by EifelMono** [davidfowl/TcpEcho#14]
I forked your project and played a little bit with it.
https://github.com/EifelMono/TcpEcho

I added a WpfClient app to send different package sizes over the socket.

Than I detect that the server  cannot receive large blocks over the socket.

I changed the _minimumBufferSize to 1024 * 2048 on the server side.

Now it is possible to receive blocks with, for example 100000 bytes.
But if I split the blocks, on the client side, in 1000 bytes blocks, the server does not receive all.

Do I something wrong or is it a bug?

![WcfClient Sample](https://raw.githubusercontent.com/EifelMono/TcpEcho/master/images/100_000%20send%20size%20100_000%20works%20but%20100_000%20sendsize%201000%20does%20not%20work.png)

**Comment by davidfowl** [comment]
I wouldn't change the buffer size, it should just work but the buffers should be split up.

**Comment by EifelMono** [comment]
But it n does not work. It hangs

**Comment by davidfowl** [comment]
What should I do the reproduce the problem in the code you sent.

**Comment by EifelMono** [comment]
# Error PipelinesServer DeadLock ??? System.InvalideOperationException in FlushAsync 

# Steps to reproduce

* start PipelinesServer
* start WpfClient
  * Connect
  * "10_000 all newline"
    * sends 10_000 chars plus newline in one block
      * this works
  * "10_000 1000 newline"
    * sends 10_000 chars plus newline in blocks with size of 1000 chars
      * this works
  * "100_000 all newline"
    * sends 100_000 chars plus newline in one block
      * this works   
  * "100_000 1000 newline"
    * sends 100_000 chars plus newline in blocks with size of 1000 chars
      * this does not works
        * DeadLock ??? System.InvalideOperationException

![System.InvalideOperationException](https://github.com/EifelMono/TcpEcho/blob/master/images/14-05-_2019_15-39-59.png)

why does github not display the image here
but here https://github.com/EifelMono/TcpEcho/blob/master/readme.md

**Comment by davidfowl** [comment]
This deadlock situation should be fixed with later versions of System.IO.Pipelines. In the past, this happened when the limits of the pipe conflicted with the maximum message size allowed by the protocol.
