### ISSUE TITLE
Get Single Element at Position from ReadOnlySequence<byte>

### ISSUE THREAD

**Issue by softworkz** [davidfowl/TcpEcho#15]
I'm trying to port a protocol parser to using a StreamPipeReader and the ReadOnlySequence<byte> buffers that I get from there.

During that process I regularly need to look ahead, e.g. determine the byte value in the stream like 100 bytes ahead (of course taking care that the buffer never gets too small for that).

Now I've spent a lot of time trying to find out how to accomplish that simple task of obtaining the value of an element at a specific position in the ReadOnlySequence.

I found absolutely no way of doing this (in a simple way). I even backported the new SequenceReader to netcore 2.2, but it doesn't seem to have that functionality either.

What am I missing here?

PS: I'm aware that I could iterate over buffer segments or advance and rewind with the SequenceReader, but that's totally crazy for simply getting an element at position x.
I read the blog post about how things would be getting a lot easier, but right now it rather seems like the opposite would be true (unless you're simply copying from one pipeline stream to another one like in all those samples).

**Comment by davidfowl** [comment]
> During that process I regularly need to look ahead, e.g. determine the byte value in the stream like 100 bytes ahead (of course taking care that the buffer never gets too small for that).

Like 100 bytes ahead or exactly 100 bytes ahead? What kind of parser are you writing? 

> Now I've spent a lot of time trying to find out how to accomplish that simple task of obtaining the value of an element at a specific position in the ReadOnlySequence.

```C#
sequence.GetPosition(100).First.Span[0]
```

PS: Copying 100 bytes to a stackalloced buffer is absolutely fine as well.

> PS: I'm aware that I could iterate over buffer segments or advance and rewind with the SequenceReader, but that's totally crazy for simply getting an element at position x.

You could avoid the rewind by storing a copy of the SequenceReader, then restoring it once you found the 100'th element.

Can you paste some sample code? I'm interested to see what kind of parser you're writing (jumping to an exact position in the buffer without a scan seems odd).

PS: Let me know if this helps: https://github.com/davidfowl/DocsStaging/blob/master/Buffers.md

**Comment by softworkz** [comment]
> > During that process I regularly need to look ahead, e.g. determine the byte value in the stream like 100 bytes ahead (of course taking care that the buffer never gets too small for that).
> 
> Like 100 bytes ahead or exactly 100 bytes ahead? What kind of parser are you writing?
> 

An mpeg transport stream parser or rather processing pipeline. I think it's quite an interesting implementation combining both Pipeline and DataFlow APIs.

Data input (can come from various sources) is handled via pipelines. Packets are created from the pipeline data and run through a DataFlow graph. Whatever comes out at the end of the graph is put in a pipeline again for output processing (again, various options).
This is all completed by now and working pretty well.

But the original (and without Pipelines api quite trivial) problem to solve was this:

Packets are of fixed length **FL** and start with a certain sync byte **SB**.
To synchronize, I read byte by byte. When I find SB, I check the next 5 assumed packet start positions (pos + FL, pos + 2*FL, pos + 3*FL, etc.).
IF these match, I assume I'm in sync and start decoding packets until an error occurs and the resync procedure starts again.


> > Now I've spent a lot of time trying to find out how to accomplish that simple task of obtaining the value of an element at a specific position in the ReadOnlySequence.
> 
> ```cs
> sequence.GetPosition(100).First.Span[0]
> ```

That does not work. GetPosition returns a SequencePosition object which:
- is pretty useless and
- doesn't have a 'First' property

I turned to use the SequenceReader for this, but it doesn't really make things easier as it is promised to do. Instead, it provides almost the same mess of an API as the ReadOnlySequence does.

Those are the most counter-intuitive API's I've ever seen. I'm a former MVP and over the many years I can't remember having seen anything like this as a public API.
It had delayed my work for several days. There were so many points I had to wonder about and figure out how it's meant to work which was only possible by studying all the source code.
One of the most perverted things was that I could not understand why the internal code could do certain things that I could not do with the public API. After a long search I found that (at least in some cases) the **position object can be cast to a** byte array(or memory or span, I don't remember). This is ridiculous. Even from a perspective focusing on the internal code only.


On the good site: The provided functionality is great and very helpful - especially for  optimizing performance, as - besides the read/write synchronization - it allows independence for the chunk size and frequency of data processing between source and target. For example, file source and network source imply very different characteristics from which the input to the DataFlow graph must be isolated. I could tell more in case you're interested.

**Comment by davidfowl** [comment]
> I turned to use the SequenceReader for this, but it doesn't really make things easier as it is promised to do. Instead, it provides almost the same mess of an API as the ReadOnlySequence does.

That's good feedback and it would be great to have an issue filed on (https://github.com/dotnet/corefx) detailing the specific scenario with code. It'll help the team better understand the issue.

> Packets are of fixed length FL and start with a certain sync byte SB.
To synchronize, I read byte by byte. When I find SB, I check the next 5 assumed packet start positions (pos + FL, pos + 2FL, pos + 3FL, etc.).
IF these match, I assume I'm in sync and start decoding packets until an error occurs and the resync procedure starts again.

Great! That's what I needed. Any sample code would also be appreciated.

> That does not work. GetPosition returns a SequencePosition object which:

My bad, I only realized I pasted the wrong code after I went to bed:

```C#
sequence.Slice(sequence.GetPosition(100)).First.Span[0]
```

> Those are the most counter-intuitive API's I've ever seen. I'm a former MVP and over the many years I can't remember having seen anything like this as a public API.
It had delayed my work for several days. There were so many points I had to wonder about and figure out how it's meant to work which was only possible by studying all the source code.
One of the most perverted things was that I could not understand why the internal code could do certain things that I could not do with the public API. 

I don't disagree. Initially when we designed the API the multi segment vs single segment problem came up and we knew it would be a problem but the APIs are hard to use without copying to a contiguous buffer. To mitigate some of that, we optimized for scenarios we had experience with (text and length prefixed buffers) but also hoped it covered enough scenarios.

That coupled with missing docs is kind of the death knell. Hopefully the docs I linked make it more obvious how to approach the API even if it doesn't solve your problem immediately.

> After a long search I found that (at least in some cases) the position object can be cast to a byte array(or memory or span, I don't remember). This is ridiculous. Even from a perspective focusing on the internal code only.

Don't do that, the code will break when we make changes to the implementation. [There are APIs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.sequencemarshal?view=netstandard-2.1) you can use to get the data out of the `ReadOnlySequence<T>` if you need access to the raw data (which you don't in this case).

**Comment by davidfowl** [comment]
Here's my take on the algorithm you have:

> _Packets are of fixed length FL and start with a certain sync byte SB.
To synchronize, I read byte by byte. When I find SB, I check the next 5 assumed packet start positions (pos + FL, pos + 2FL, pos + 3FL, etc.).
IF these match, I assume I'm in sync and start decoding packets until an error occurs and the resync procedure starts again._

```C#
static SequencePosition? FindStartOfFrame(ReadOnlySequence<byte> buffer, byte syncByte, int frameLength, int numFrames)
{
    // Find the sync byte position
    SequencePosition? position = buffer.PositionOf(syncByte);

    if (position == null)
    {
        // Didn't find it so we don't have a frame
        return null;
    }

    // Slice the position
    buffer = buffer.Slice(position.Value);

    for (var i = 0; i < numFrames; ++i)
    {
        // The sequence is invalid in 2 cases
        // - We don't have enough bytes to make up a valid frame or 
        // - We the first byte isn't a syncByte
        if (buffer.Length < frameLength || buffer.First.Span[0] != syncByte)
        {
            return null;
        }

        // Slice the buffer assuming this is a valid frame
        buffer = buffer.Slice(frameLength);
    }

    // Return the start
    return position.Value;
}
```

**Comment by davidfowl** [comment]
Here's what it would look like with the `SequenceReader`:

```C#
static SequencePosition? FindStartOfFrame(ReadOnlySequence<byte> buffer, byte syncByte, int frameLength, int numFrames)
{
    var reader = new SequenceReader<byte>(buffer);
    SequencePosition? position = null;

    while (!reader.End)
    {
        if (reader.CurrentSpan[reader.CurrentSpanIndex] == syncByte)
        {
            position = reader.Position;
            break;
        }

        reader.Advance(1);
    }

    if (position == null)
    {
        return null;
    }

    for (var i = 0; i < numFrames; ++i)
    {
        // The sequence is invalid in 2 cases
        // - We don't have enough bytes to make up a valid frame or 
        // - We the first byte isn't a syncByte
        if (reader.Remaining < frameLength || reader.CurrentSpan[reader.CurrentSpanIndex] != syncByte)
        {
            return null;
        }

        // Slice the buffer assuming this is a valid frame
        reader.Advance(frameLength);
    }

    // Return the start
    return position.Value;
}
```

Though I'd recommend trying to use `PositionOf` since it's a vectorized search (instead of going byte by byte). 

There are probably many other ways to write this form of logic and I'll try to capture some of that in my doc. Thanks for the examples!

**Comment by softworkz** [comment]
Well, yeah, that's close..

One of the big pain points were the SequencePosition objects. They are objects on one side and on the other side they have an integer property. But that property cannot be trusted as it appears to make sense for a moment and in the other moment it's totally wrong.
This doesn't model something that I can understand and work with as a POSITION. An entity that is meant to describe a position needs to have the ability to be put into relation to another one of its kind. And this is not the case here.

At some point I wanted to be able to do some calculation using some real position values and after many unsuccessful experiments with SequencePosition object, I decided to completely avoid them.

This is what I finally came up with:

```cs
private bool FindSync(SequenceReader<byte> reader, bool isCompleted)
{
    // To correctly synchronize, we want at least the amount of 'RequiredSyncPackets' packets in the buffer
    // except when we're at the end of the stream
    var requiredBufferSize = isCompleted ? this.packetSize : Constants.RequiredSyncPackets * this.packetSize;

    try
    {
        while (reader.Remaining >= requiredBufferSize)
        {
            var ok = reader.TryPeek(out byte peekValue) && peekValue == Constants.SyncByte;

            var startPos = reader.Consumed;

            for (var i = 0; ok && i <= Constants.RequiredSyncPackets && this.packetSize < reader.Remaining; i++)
            {
                reader.Advance(this.packetSize);
                ok = reader.TryPeek(out peekValue) && peekValue == Constants.SyncByte;
            }

            reader.Rewind(reader.Consumed - startPos);

            if (ok)
            {
                return true;
            }

            while (!ok && reader.Remaining > requiredBufferSize)
            {
                reader.Advance(1);
                ok = reader.TryPeek(out peekValue) && peekValue == Constants.SyncByte;
            }

            if (!ok)
            {
                return false;
            }
        }

        return false;
    }
    catch (Exception ex)
    {
        Debug.WriteLine("Problem in FindSync algorithm... : ", ex.Message);
        throw;
    }
}
```

**Comment by davidfowl** [comment]
> One of the big pain points were the SequencePosition objects. They are objects on one side and on the other side they have an integer property. But that property cannot be trusted as it appears to make sense for a moment and in the other moment it's totally wrong.
This doesn't model something that I can understand and work with as a POSITION. An entity that is meant to describe a position needs to have the ability to be put into relation to another one of its kind. And this is not the case here.

> At some point I wanted to be able to do some calculation using some real position values and after many unsuccessful experiments with SequencePosition object, I decided to completely avoid them.

Yes, the inability to treat a `SequencePosition` as interchangeable as integers makes them really hard to use. Effectively they can only be used for slicing the original `ReadOnlySequence<byte>`. Rewind can get pretty expensive for bigger segments so I wouldn't use it unless.

What's the intent of doing the Rewind?

**Comment by softworkz** [comment]
> What's the intent of doing the Rewind?

That's the position from which I need to continue reading after I've verified that the subsequent sync bytes are at the right positions.

If there was an overload for TryPeek() that takes a position offset as an argument, it would be much easier. That's one of the things I would suggest.

I guess it's way too late to do fundamental changes to the pipeline and ReadOnlySequence part. But I think that the SequenceReader is a chance to remedy some of those shortcomings. IMO, the following should happen to the SequenceReader:

- Don't work with SequencePosition objects, work with some usable position values
- Remove the behavior that one can already have with the ReadOnlySequence. Instead provide methods that are really hiding the segmentation from the consumer. For example:
  - The TryPeek overload
  - A slice method taking understandable position values.
    If the requested slice goes across segments: Temporarily copy it into a contiguous memory range and return the span for it
  - The is the pattern that should be followed: Provide typical methods that people would normally use in a way just like if it was all a contiguous memory range. 

That's what it takes IMO to make this stuff usable with joy instead of pain :-) :-)

**Comment by softworkz** [comment]
PS: I've invited you to a repo where you can see the full context

**Comment by davidfowl** [comment]
> That's the position from which I need to continue reading after I've verified that the subsequent sync bytes are at the right positions.

So this logic doesn't find the right position, it determines if the current position is the right position? That seems less efficient.

Why not just return the position of the frame from this method? That would avoid having to re-scan already scanned bytes.

> If there was an overload for TryPeek() that takes a position offset as an argument, it would be much easier. That's one of the things I would suggest.

If we made TryPeek do that it would be an `O(segments)` scan to get the data at a specific `SequencePosition`. That's actually why it's not on `ReadOnlySequence<T>` as an indexer, it's a performance trap.

> Don't work with SequencePosition objects, work with some usable position values

What change does that mean concretely?

> A slice method taking understandable position values.

Assuming you mean `ReadOnlySequence<T>.Slice` it takes both ints and positions. One has to scan, for the position, the other does not.

> If the requested slice goes across segments: Temporarily copy it into a contiguous memory range and return the span for it

What does this mean exactly? What would the consuming code look like? Isn't this just `ToArray()` (which will allocate)?

> The is the pattern that should be followed: Provide typical methods that people would normally use in a way just like if it was all a contiguous memory range.

Agreed with the caveat of avoiding performance traps. If you want to use the API like it was a contiguous buffer then `ToArray()` and deal with the generated. IMO it's not great to pretend like you are dealing with contiguous memory to make the code easy to write but be slower so we need to find the right balance of APIs to improve things.

This is great feedback. Thanks!

**Comment by davidfowl** [comment]
PS: I strongly recommend reading the docs [here](https://github.com/davidfowl/DocsStaging) to see if you're running into any of the gotchas in both buffers and pipelines. 

Some of them can have a serious impact (like security problems) if not implemented correctly.

**Comment by softworkz** [comment]
> > That's the position from which I need to continue reading after I've verified that the subsequent sync bytes are at the right positions.
> 
> So this logic doesn't find the right position, it determines if the current position is the right position? That seems less efficient.
> 
> Why not just return the position of the frame from this method? That would avoid having to re-scan already scanned bytes.

What should I do with the returned position? The SequenceReader is passed to that method and it's Position property is read-only.

At this point I should probably note that the packet size is only 188 bytes! And we're processing data at rates like up to 80 Mbps.

> If we made TryPeek do that it would be an O(segments) scan to get the data at a specific SequencePosition. That's actually why it's not on ReadOnlySequence<T> as an indexer, it's a performance trap.

No. It's not a trap. It's a necessity. It has to be done - no matter the complexity.
Now I start to understand why this API design is so close to being unusable: You didn't want to implement functionality that could shed some some bad light onto it performance-wise....

That's not a good approach, though. As mentioned, there are things that need to be done. Anyway, in my case for example, there's not point in arguing about mathematical complexity, because what happens here is that in more than 90% of all cases, the required operations are performed within a single segment and for the other 10% it's just spanning from one segment to the next, so whether the complexity calculates like 2*2 or 2^2 doesn't matter at all.

Having a SequenceReader doing things in a convenient way is not intrinsically bad just because it could give bad performance. That must be the developer's decision. But of course it needs to be documented clearly.

**Comment by davidfowl** [comment]
> No. It's not a trap. It's a necessity. It has to be done - no matter the complexity.

Nope, it's a similar reason to why `Memory<T>` and `ReadOnlyMemory<T>` don't have an indexer and you need to go through the Span.

> Now I start to understand why this API design is so close to being unusable: You didn't want to implement functionality that could shed some some bad light onto it performance-wise....

It is rough and we definitely need to make some improvements. `SequenceReader<T>` was one of those specific improvements and there are more coming.

> That's not a good approach, though. As mentioned, there are things that need to be done. Anyway, in my case for example, there's not point in arguing about mathematical complexity, because what happens here is that in more than 90% of all cases, the required operations are performed within a single segment and for the other 10% it's just spanning from one segment to the next, so whether the complexity calculates like 2*2 or 2^2 doesn't matter at all.

Then the choice is simple right? If that's the case in your scenario, if the data is in a single segment, use it and if it isn't copy to a contiguous buffer and parse.

> Having a SequenceReader doing things in a convenient way is not intrinsically bad just because it could give bad performance. That must be the developer's decision. But of course it needs to be documented clearly.

That's a philosophical argument we can agree to disagree on. If you want bad performance use ToArray and your life will get easier but you may end up paying for it in the long run.

**Comment by davidfowl** [comment]
FWIW: I'm going to file some API suggestions based on this discussion!

**Comment by davidfowl** [comment]
- https://github.com/dotnet/corefx/issues/40843
- https://github.com/dotnet/corefx/issues/40845

**Comment by softworkz** [comment]
> > That's not a good approach, though. As mentioned, there are things that need to be done. Anyway, in my case for example, there's not point in arguing about mathematical complexity, because what happens here is that in more than 90% of all cases, the required operations are performed within a single segment and for the other 10% it's just spanning from one segment to the next, so whether the complexity calculates like 2*2 or 2^2 doesn't matter at all.
> 
> Then the choice is simple right? If that's the case in your scenario, if the data is in a single segment, use it and if it isn't copy to a contiguous buffer and parse.

(there can also be cases with thosands of unusable packets...)

This is what I expect from the SequenceReader to do for me. Because otherwise I'd get soon into the direction of managing my own buffer pool without pipelines - just like you would do it in the classic way. 

> > Having a SequenceReader doing things in a convenient way is not intrinsically bad just because it could give bad performance. That must be the developer's decision. But of course it needs to be documented clearly.
> 
> That's a philosophical argument we can agree to disagree on. If you want bad performance use ToArray and your life will get easier but you may end up paying for it in the long run.

Yes, I would agree that it is debatable in case of the ReadOnlySequence case.

But I see no point in creating an additional API on top of it (SequenceReader) when it is just more-or-less resembling the behavior that already exists anyway.
At this time, the SequenceReader has a nothing but a few tiny benefits over ReadOnlySequence, but essentially - it's the same story just with different words.

And it could be something much better IMO. It could be the candy on top of this opening up this API for more than just Microsoft internals and a few masochists ;-)

**Comment by softworkz** [comment]
> PS: I strongly recommend reading the docs [here](https://github.com/davidfowl/DocsStaging) to see if you're running into any of the gotchas in both buffers and pipelines.

I should probably add that our development is already completed in that area and we got a very stable solution able to process high data rates with minimal cpu usage. It will be released to market shortly.

By the way: During profiling I hadn't seen any performance penalty from using the .Rewind method.

**Comment by softworkz** [comment]
> * [dotnet/corefx#40843](https://github.com/dotnet/corefx/issues/40843)
> * [dotnet/corefx#40845](https://github.com/dotnet/corefx/issues/40845)

Great, that's the right direction.

Now, let's look at something different:

- We have a SequenceReader at a certain position
- We want to read a 4 byte integer value starting from this position
- There are nice helper methods for this available, like: 
`BinaryPrimitives.ReadUInt32BigEndian(byteSpan)`

It's basically a simple thing, but how do you do it?

- You cannot simply do:
`BinaryPrimitives.ReadUInt32BigEndian(reader.UnreadSpan.Slice(0, 4))`
 Because you could hit a segment boundary
- You don't want to allocate a byte buffer each time, execute TryCopyMultisegment only to parse the Int32 from it (at least not in the majority of cases where there's no segment boundary)
- But you also don't want to have your code full of conditional statements to handle this as you may have a ton of those BinaryPrimitives calls.


At this point, we're arriving exactly at the requirement for the method that I've described previously:

```cs
public partial ref struct SequenceReader<T>
{
    /// <summary>
    /// Returns a span covering the specified range.
    /// If required, a temporary buffer is created for the returned span.
    /// </summary>
    ReadOnlySpan<T> GetSpan(int offset, int length);
}

```

IMO, this one is even more important than the other two proposals that you've posted already.

**Comment by davidfowl** [comment]
You use the built in methods that already do it for you https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereaderextensions?view=netcore-3.0.

**Comment by softworkz** [comment]
I need unsigned integers in most cases..

No, that's not sufficient. .NET Core 3.0 adds hundreds of new .TryParse() overloads working on spans, and also you will want to write your own parsing methods etc.

Needing a contiguous range of data from a SequenceReader is a central requirement.
It cannot be solved with five extension methods.

**Comment by zmj** [comment]
> Now, let's look at something different:
> 
> * We have a SequenceReader at a certain position
> * We want to read a 4 byte integer value starting from this position
> * There are nice helper methods for this available, like:
>   `BinaryPrimitives.ReadUInt32BigEndian(byteSpan)`
> 
> It's basically a simple thing, but how do you do it?
> 
> * You cannot simply do:
>   `BinaryPrimitives.ReadUInt32BigEndian(reader.UnreadSpan.Slice(0, 4))`
>   Because you could hit a segment boundary
> * You don't want to allocate a byte buffer each time, execute TryCopyMultisegment only to parse the Int32 from it (at least not in the majority of cases where there's no segment boundary)
> * But you also don't want to have your code full of conditional statements to handle this as you may have a ton of those BinaryPrimitives calls.

I had a similar need and wrote some extensions to cover this: https://github.com/zmj/rsync-delta/blob/master/rsync.delta/pipes/SequenceExtensions.cs#L41

I'm not sure if this is a good approach - it's tough to discover best practices for pipelines at this point. Looking forward to the final docs :)

No SequenceReader involved since I'm targeting netstandard 2.0.

**Comment by davidfowl** [comment]
Please do file an API suggestions for this stuff. We'll review and get them added 😄

**Comment by softworkz** [comment]
> No SequenceReader involved since I'm targeting netstandard 2.0.

We're using netstandard as well, that's why I've thrown the SequenceReader source code directly into our project ;-)

> I'm not sure if this is a good approach - it's tough to discover best practices for pipelines at this point. Looking forward to the final docs :)

It takes more than just docs. I think it also takes good examples and currently, David's examples are very - let's say - focused.

@davidfowl - How about if you would try to create some kind of parsing example based on SequenceReader?

I think some basic JSON or XML parser would be a good idea. It would take a char sequence instead of a byte sequence, but it would be easier to understand than some kind of binary format because everybody knows those formats.
Of course I don't mean to create a complete and usable xml parser - just a simple example, parsing elements and their attributes as string values.
What do you think?

PS: I've submitted a proposal for the mentioned API here: https://github.com/dotnet/corefx/issues/40885 - maybe you could do the appropriate labeling...

**Comment by davidfowl** [comment]
We rewrote the form and http/1.1 parser in ASP.NET Core to use the SequenceReader. We parse a length prefixed buffer in SignalR and the built in methods work well for that.

Going forward we’ll also look at the moving the multipart reader.

**Comment by davidfowl** [comment]
Since this discussion, we've added a bunch of APIs to help address some of this. I'm gonna close this out. Thanks for the discussion.

**Comment by softworkz** [comment]
Thanks for your assistance in getting those added 🥇
