### ISSUE TITLE
How I will split data read using PipeReader when my messages are binary (protobuf serialized)

### ISSUE THREAD

**Issue by msbasanth** [davidfowl/TcpEcho#17]
Hi,

I tried using Pipeline in our project where we have serialized binary send to server and server de-serializes it. The difficulty I am facing is with splitting the data at PipeReader. This sample used '\n' as the delimiter in a binary data I may not be able to use '\n' as delimiter (ASCII value 10).

We normally rely on EndOfMessage to identify the one client message and then process it. 

` 
`do {

       response = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), cancelToken);
        message.AddRange(new ArraySegment<byte>(buffer, 0, response.Count));
    } while (!response.EndOfMessage);`

When it comes to Pipeline implementation, writing thread will continuously push data to Pipeline. But unable to find EndOfMessage for splitting the messages using at PipeReader thread.

Looks to be a standard problem any good approaches to follow when we want to send and receive binary data? Is there a better way to parse the client send data without using delimiter?

Regards
Basanth

**Comment by davidfowl** [comment]
Take a look at some of the docs in progress here and see if it helps:

https://github.com/davidfowl/DocsStaging

**Comment by davidfowl** [comment]
> We normally rely on EndOfMessage to identify the one client message and then process it.

Pipelines is for streaming data, if that EndOfMessage doesn't make it into the Stream in some form then there's no way to know on the reader side where it ends.

> Looks to be a standard problem any good approaches to follow when we want to send and receive binary data? Is there a better way to parse the client send data without using delimiter?

Are you reading from already framed data? What's framing it? If you can change the entire thing to use pipelines then you would just parse the EndOfMessage frame yourself. 

If you're using the WebSocket API (which I know has framing) then there's no obvious way to signal end of the message without writing something into the pipe as data
