### ISSUE TITLE
Extended sample with Protobuf binary data transfer observations little different from here

### ISSUE THREAD

**Issue by msbasanth** [davidfowl/TcpEcho#18]
Hi,

I modified TcpEcho sample with Protobuf ReadOnlySequenceReader and checked the performance.

Test Environment
* .Net Framework 4.7.2
* protobuf-net v3.0.0-alpha.32
* Commandline: 
Client.exe MessageSize
PipelinesServer.exe MessageSize
SocketServer.exe MessageSize

* Used message sizes - 32, 128, 512, 1024, 2048, 4096, 8192, 10000
* Used Release AnyCPU for taking readings by sending same protobuf buffer 1_000_00 times.

Message Size | Stream| Pipeline
-- | -- | --
32 | 3.71 | 4.80
128 | 3.81 | 4.70
512 | 4.11 | 5.03
1024 | 4.09 | 5.12
2048 | 4.46 | 5.68
4096 | 4.78 | 5.75
8192 | 5.36 | 5.98
10000 | 5.64 | 6.60

I additionally have Protobuf deserialization in server side. But reading shows Socket version performs better with deserialization consistently with message sizes (32 bytes - 10000 bytes).

Please have a look: https://github.com/msbasanth/Pipelines.TcpEcho.Protobuf

I am using BufferSize equal to message size instead of fixed size(512). How we decide on the minimum buffer size to set?

Regards
Basanth

**Comment by davidfowl** [comment]
Very nice investigation! Any chance you could run it agasint .NET Core 3.0 and the latest version of pipelines. .NET Framework doesn't have any of the same level of optimizations .NET Core has so it would be good to understand any differences there.

Some other reasons for overhead off the top of my head:
- Pipelines will add some overhead over using Streams directly (especially for contiguous buffers). One thing you could try is copying the buffer into a single byte[] to understand how much overhead is in the ProtoReader.Create is. I'd also use the same logic on both the Stream version and the version using pipelines.
- There are some improvements in the later versions that will remove some allocations.
    - The default memory pool does allocated per call to Rent. This is gone now.
    - Linked list segments weren't pooled, now they are.
- It's possible there's more thread pool dispatching happening in the Pipelines version and there's more overhead in doing so. Calling FlushAsync will dispatch the reader to the thread pool (which isn't as optimized on .NET Framework).

I'd profile the pipelines version, both memory and cpu profile to see where time is being spent. How can I replicate your numbers? Did you just manually run the application with different buffer sizes?

> I am using BufferSize equal to message size instead of fixed size(512). How we decide on the minimum buffer size to set?

That is a minimum size 512 is a minimum, not necessarily what buffer you'll end up getting. It's just a number passed to the memory pool Rent as a minimum. If you increase the buffer size you'll end up getting heap allocated buffers if the pool can't satisfy that amount in a single call to Rent. 

Instead, think of that size as a minimum size buffer you'd want a read to fulfill, not necessarily the resulting size of the message. There's another setting called minimum segment size that can be used to determine the size of the pipe's internal segments that it uses to track memory.

Hope this helps
