### ISSUE TITLE
Implementation for a similar requirement

### ISSUE THREAD

**Issue by francisminu** [davidfowl/TcpEcho#6]
Hi,

This might be along the same lines as the above issue, where you have mentioned that this is just a starter.
I am currently trying to implement the Pipelines and is finding it difficult.

The requirement is, we have a constantly interacting server and client. So, I need to write to the pipes from Socket or Stream as and when Data comes in meanwhile, not completing the WRITE operation and also need the READ to happen when a Write has been done. And once a READ is done, if it has a proper message, I have some further processing to be done with the same, so I need the task to return some data.

At present, the WRITE loop never completes and as a result, I am unable to return the result. The READ never returns the result.

Any pointer would be really helpful.

Thanks!

**Comment by davidfowl** [comment]
I'm not sure what you need to do. Let me know if reading this helps https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines
